### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by AbdullahMahmoud23** [AbdullahELyamany/Django-To-Do-List-Website-With-User-Registration#1]
To-Do List App Using Django

**Comment by AbdullahELyamany** [comment]
...

**Comment by AbdullahELyamany** [comment]
![add_new_task](https://github.com/AbdullahELyamany/Django-To-Do-List-Website-With-User-Registration/assets/124623013/33e22d9e-e3e6-41be-beac-9d444536d7e5)
![delete_task](https://github.com/AbdullahELyamany/Django-To-Do-List-Website-With-User-Registration/assets/124623013/61b0e9ba-138a-472e-9a8f-4e8abdce9e39)
![edit_task](https://github.com/AbdullahELyamany/Django-To-Do-List-Website-With-User-Registration/assets/124623013/88a6f534-beb1-4344-a9a9-bd43b9ce03c8)
![login](https://github.com/AbdullahELyamany/Django-To-Do-List-Website-With-User-Registration/assets/124623013/07286d29-585a-4a7a-9d92-7dcec133f9fd)
![register](https://github.com/AbdullahELyamany/Django-To-Do-List-Website-With-User-Registration/assets/124623013/c16d38e7-dec5-4e4c-b447-0c0cc552fd0b)
![task_list_by_search](https://github.com/AbdullahELyamany/Django-To-Do-List-Website-With-User-Registration/assets/124623013/63946658-c601-4bbf-986a-645e77b164e8)
![tasks_list_main_page](https://github.com/AbdullahELyamany/Django-To-Do-List-Website-With-User-Registration/assets/124623013/f50e574c-a82e-4b4f-900d-d3b289646f28)
